src/crudl/crudl/apps/ideas/urls.py
from django.urls import path

from .views import (
    # IdeaList,
    # idea_list,
    IdeaListView,
    IdeaDetail,
    add_or_change_idea,
    delete_idea,
    idea_handout_pdf,
    download_idea_picture
)

urlpatterns = [
    path("", IdeaListView.as_view(), name="idea_list"),
    path("add/", add_or_change_idea, name="add_idea"),
    path("<uuid:pk>/", IdeaDetail.as_view(), name="idea_detail"),
    path("<uuid:pk>/change/", add_or_change_idea, name="change_idea"),
    path("<uuid:pk>/delete/", delete_idea, name="delete_idea"),
    path("<uuid:pk>/handout/", idea_handout_pdf, name="idea_handout"),
    path("<uuid:pk>/download-picture/", download_idea_picture, name="download_idea_picture"),
]

src/crudl/crudl/apps/music/urls.py
from django.urls import path
from .feeds import SongFeed
from .views import SongListView, SongDetailView

app_name = "music"

urlpatterns = [
    path("", SongListView.as_view(), name="song_list"),
    path("<uuid:pk>/", SongDetailView.as_view(), name="song_detail"),
    path("rss/", SongFeed(), name="song_rss"),
]

src/crudl/crudl/apps/news/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView

urlpatterns = [
    path("article/", ArticleListView.as_view(), name="article_list"),
    path("<uuid:pk>/", ArticleDetailView.as_view(), name="article_detail"),
]

src/crudl/crudl/urls.py
from nis import cat
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.sitemaps import GenericSitemap
import debug_toolbar
from crudl.apps.core import views as core_views
from crudl.apps.external_auth.views import (index, dashboard, logout)
from crudl.apps.category import views as category_views
from crudl.apps.music.models import Song
from crudl.apps.music.views import RESTSongList, RESTSongDetail


class CrudlSitemap(GenericSitemap):
    limit = 50

    def location(self, obj):
        return obj.get_url_path()

song_info_dict = {
    "queryset": Song.objects.all(),
    "date_field": "modified",
}
sitemaps = {"music": CrudlSitemap(song_info_dict, priority=1.0)}

urlpatterns = [
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("rest-api/songs/", RESTSongList.as_view(), name="rest_song_list"),
    path("rest-api/songs/<uuid:pk>/", RESTSongDetail.as_view(), name="rest_song_detail"),
    path("sitemap.xml", sitemaps_views.index, {"sitemaps": sitemaps}),
    path("sitemap-<str:section>.xml", sitemaps_views.sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

urlpatterns += i18n_patterns(
    path("", index, name="index"),
    path("dashboard/", dashboard, name="dashboard"),
    path("logout/", logout, name="logout"),
    path("", include("social_django.urls")),
    path("", lambda request: redirect("ideas:idea_list")),
    # path("", lambda request: redirect("locations:location_list")),
    #path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ideas/", include(("crudl.apps.ideas.urls", "ideas"), namespace="ideas")),
    path("news/", include(("crudl.apps.news.urls", "news"), namespace="news")),
    path("locations/", include(("crudl.apps.locations.urls", "locations"), namespace="locations")),
    path("search/", include("haystack.urls")),
    path("js_settings/", core_views.js_settings, name="js_settings"),
    path("upload-file/", core_views.upload_file, name="upload_file"),
    path("likes/", include(("crudl.apps.likes.urls", "likes"), namespace="likes")),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("management/", admin.site.urls),
    path("idea-categories/", category_views.IdeaCategoryListView.as_view(), name="idea_categories",),
    path("songs/", include("crudl.apps.music.urls", namespace="music")),
    path("viral-videos/", include("crudl.apps.viral_videos.urls", namespace="viral_videos")),
)
urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT)

src/crudl/crudl/apps/admin_honeypot_fix/models.py
from django.db import models

# Create your models here.

src/crudl/crudl/apps/auth_extra/models.py
from django.db import models

# Create your models here.

src/crudl/crudl/apps/category/models.py
from multiprocessing import parent_process
from django.db import models
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel
from mptt.fields import TreeForeignKey
from treebeard.mp_tree import MP_Node
from crudl.apps.core.models import CreationModificationDateBase
from crudl.apps.core.model_fields import TranslatedField


class Category(MP_Node, MPTTModel, CreationModificationDateBase):
    parent = TreeForeignKey("self", on_delete=models.CASCADE, blank=True, null=True, related_name="children")
    title = models.CharField(_("Title"),max_length=200)
    translated_title = TranslatedField("title")
    
    class Meta:
        ordering = ["tree_id", "lft"]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
    
    class MPTTMeta:
        order_insertion_by = ["title"]
    
    def __str__(self):
        return self.title


class CategoryTranslations(models.Model):
    category = models.ForeignKey(
        Category,
        verbose_name = _("Category"),
        on_delete = models.CASCADE,
        related_name = "translations"
    )
    language = models.CharField(_("Language"), max_length = 7)
    title = models.CharField(_("Title"), max_length=200)

    class Meta:
        verbose_name = _("Category Translations")
        verbose_name_plural = _("Category Translations")
        ordering = ["language"]
        unique_together = [["category", "language"]]
    
    def __str__(self):
        return self.title

src/crudl/crudl/apps/external_auth/models.py
from django.db import models

# Create your models here.

src/crudl/crudl/apps/guerrilla_patches/models.py
from django.db import models
from django.utils import text
from transliterate import slugify

text.slugify = slugify

src/crudl/crudl/apps/search/models.py
from django.db import models

# Create your models here.

src/crudl/crudl/apps/ideas/forms.py
from re import template
from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model
from crispy_forms import bootstrap, helper, layout
from pkg_resources import require
from mptt.forms import TreeNodeChoiceField
from crudl.apps.category.models import Category
from crudl.apps.core.form_fields import MultipleChoiceTreeField
from .models import Idea, IdeaTranslations, RATING_CHOICES

User = get_user_model()


class IdeaSearchForm(forms.Form):
    q = forms.CharField(label=_("Search for"), required=False)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)
        
        self.helper = helper.FormHelper()
        self.helper.form_action = self.request.path
        self.helper.form_method = "GET"
        self.helper.layout = layout.Layout(
            layout.Field("q", css_class="input-block-level"),
            layout.submit("search", _("Search")),
        )


class IdeaForm(forms.ModelForm):
    categories = MultipleChoiceTreeField(
        label= _("Categories"),
        required=False,
        queryset=Category.objects.all(),
    )
    class Meta:
        model = Idea
        exclude = ["author"]
    
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)
        
        self.fields["categories"].widget = forms.CheckboxSelectMultiple()
        title_field = layout.Field(
            "title", css_class="input-block-level"
        )
        content_field = layout.Field(
            "content", css_class="input-block-level", rows="3"
        )
        main_fieldset = layout.Fieldset(
            _("Main data"), title_field, content_field
        )
        picture_field = layout.Field(
            "picture", css_class = "input-block-level"
        )
        format_html = layout.HTML(
            """{% include "ideas/includes/picture_guidelines.html" %}"""
        )
        picture_fieldset = layout.Fieldset(
            _("Picture"),
            picture_field,
            format_html,
            title=_("Image upload"),
            css_id="picture_fieldset",
        )
        categories_field = layout.Field(
            "categories",
            template = "core/includes/checkboxselectmultiple_tree.html",
        )
        categories_fieldset = layout.Fieldset(
            _("Categories"), categories_field,
            css_id="categories_fieldset"
        )
        inline_translations = layout.HTML(
            """{% include 'ideas/forms/translations.html' %}"""
        )
        submit_button = layout.Submit("save", _("Save"))
        actions = bootstrap.FormActions(submit_button)
        self.helper = helper.FormHelper()
        self.helper.form_action = self.request.path
        self.helper.form_method = "POST"
        self.helper.layout = layout.Layout(
            main_fieldset,
            inline_translations,
            picture_fieldset,
            categories_fieldset,
            actions
        )
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.author = self.request.user
        if commit:
            instance.save()
            self.save_m2m()
        return instance


class IdeaFilterForm(forms.Form):
    author = forms.ModelChoiceField(
        label=_("Author"),
        required=False,
        queryset=User.objects.annotate(
            idea_count=models.Count("authored_ideas")
        ).filter(idea_count__gt=0)
    )
    category = TreeNodeChoiceField(
        label =_("Category"),
        required=False,
        queryset = Category.objects.all(),
        level_indicator = mark_safe("&nbsp;&nbsp;&nbsp;&nbsp;")
    )
    rating = forms.ChoiceField(
        label =_("Rating"), required=False, choices=RATING_CHOICES
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        author_field = layout.Field("author")
        category_field = layout.Field("category")
        rating_field = layout.Field("rating")
        submit_button = layout.Submit("filter", _("Filter"))
        actions = bootstrap.FormActions(submit_button)
        main_fieldset = layout.Fieldset(_("Filter"), author_field, category_field, rating_field, actions,)

        self.helper = helper.FormHelper()
        self.helper.form_method = "GET"
        self.helper.layout = layout.Layout(main_fieldset)


class IdeaTranslationsForm(forms.ModelForm):
    language = forms.ChoiceField(
        label=_("Language"),
        choices=settings.LANGUAGES_EXCEPT_THE_DEFAULT,
        required=True,
    )
    
    class Meta:
        model = IdeaTranslations
        exclude = ["idea"]
    
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

        id_field = layout.Field("id")
        language_field = layout.Field(
            "language", css_class="input-block-level"
        )
        title_field = layout.Field(
            "title", css_class="input-block-level"
        )
        content_field = layout.Field(
            "content", css_class="input-block-level", rows="3"
        )
        delete_field = layout.Field("DELETE")
        main_fieldset = layout.Fieldset(
            _("Main dta"),
            id_field,
            language_field,
            title_field,
            content_field,
            delete_field,
        )
        self.helper = helper.FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = layout.Layout(main_fieldset)

src/crudl/crudl/apps/locations/forms.py
import os
from django import forms
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.files.storage import default_storage
from crispy_forms import bootstrap, helper, layout
from .models import Location


class LocationForm(forms.ModelForm):
    picture = forms.ImageField(label=_("Picture"), max_length=255, widget=forms.FileInput(), required=False)
    picture_path = forms.CharField(max_length=255, widget=forms.HiddenInput(), required=False)
    latitude = forms.FloatField(label=_("Latitude"), help_text=_("Latitude (Lat.) is the angle between any point and the equator (north pole is at 90; south pole is at -90)."), required=False,)
    longitude = forms.FloatField(label=_("Longitude"), help_text=_("Longitude (Long.) is the angle east to west of an arbitary point on Earth from Greenwich (UK), which is the international zero-longitude point (longitude=0 degree). The anti-meridian of Greenwich is both 180 (direction to east) and -180 (direction to west)."), required=False,)
    class Meta:
        model = Location
        exclude = ["geoposition", "rating"]
    
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)
        geoposition = self.instance.get_geoposition()
        if geoposition:
            self.fields["latitude"].initial = geoposition.latitude
            self.fields["longitude"].initial = geoposition.longitude
        name_field = layout.Field("name", css_class="input-block-level")
        description_field = layout.Field("description", css_class="input-block-level", rows="3")
        main_fieldset = layout.Fieldset(_("Main data"), name_field, description_field)
        picture_field = layout.Field("picture", data_url=reverse("upload_file"), template="core/includes/file_uplod_field.html",)
        picture_path_field = layout.Fieldset("picture_path")
        picture_fieldset = layout.Fieldset(_("Picture"), picture_field, picture_path_field, title=_("Picture upload"), css_id="picture_fieldset",)
        street_address_field = layout.Field("street_address", css_class="input-block-level")
        street_address2_field = layout.Field("street_address2", css_class="input-block-level")
        postal_code_field = layout.Field("postal_code", css_class="input-block-level")
        city_field = layout.Field("city_field", css_class="input-block-level")
        country_field = layout.Field("country_field", css_class="input-block-level")
        latitude_field = layout.Field("lantitude_field", css_class="input-block-level")
        longitude_field = layout.Field("longitude_field", css_class="input-block-level")
        address_fieldset = layout.Fieldset(_("Address"), street_address_field, street_address2_field, postal_code_field, city_field, country_field, latitude_field, longitude_field,)
        submit_button = layout.Submit("save", _("Save"))
        actions = bootstrap.FormActions(layout.Div(submit_button, css_class="col"))
        self.helper = helper.FormHelper()
        self.helper.form_action = self.request.path
        self.helper.form_method = "POST"
        self.helper.attrs = {"noValidate":"noValidate"}
        self.helper.layout = layout.Layout(main_fieldset, picture_fieldset, address_fieldset, actions)
    
    def clean(self):
        cleaned_data = super().clean()
        picture_path = cleaned_data["picture_path"]
        if not self.instance.pk and not self.files.get("picture") and not picture_path:
            raise forms.ValidationError(_("Please choose an image."))
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        picture_path = self.cleaned_data["picture_path"]
        if picture_path:
            temporary_image_path = os.path.join("temporary_uploads", picture_path)
            file_obj = default_storage.open(temporary_image_path)
            instance.picture.save(picture_path, file_obj, save=False)
            default_storage.delete(temporary_image_path)
        latitude = self.cleaned_data["latitude"]
        longitude = self.cleaned_data["longitude"]
        if latitude is not None and longitude is not None:
            instance.set_geoposition(longitude=longitude, latitude=latitude)
        if commit:
            instance.save()
            self.save_m2m()
        return instance

src/crudl/crudl/apps/music/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Song


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = "__all__"


class SongFilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        artist_choices = [
            (artist, artist) for artist in sorted(
                Song.objects.values_list("artist", flat=True).distinct(),
                key=str.casefold
            )
        ]
        self.fields["artist"] = forms.ChoiceField(label= _("Artist"), choices=artist_choices, required=False,)

src/crudl/crudl/apps/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/crudl/crudl/templates/ideas/base_pdf.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap Css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% trans "" %}</title>
    <style>
        @page{
            size: "A4";
            margin: 2.5cm 1.5cm 3.5cm 1.5cm;
        }
        footer{
            position: fixed;
            bottom: -2.5cm;
            width: 100%;
            text-align: center;
            font-size: 10pt;
        }
        footer img{
            height: 1.5cm;
        }
    </style>
    {% block meta_tags %}{% endblock meta_tags %}
</head>
<body>
    <main class="container">
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <img alt="" src="data:image/svg+xml, {# url-encoded SVG logo goes here #}" />
    </br>
    {% trans "Printed from Crudl" %}
    </footer>
</body>
</html>

src/crudl/crudl/templates/ideas/idea_detail.html
{% extends "crudl/base.html" %}
{% load i18n json_ld %}
{% block meta_tags %}
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ WEBSITE_URL }} {{ request.path }}" />
    <meta property="og:title" content="{{ idea.translated_title }}" />
    {% if idea.picture_social %}
        <meta property="og:image" content="{{ idea.picture_social_url }}" />
        <!-- Next tags are optional but recommended -->
        <meta property="og:image:width" content="{{ idea.picture_social.width }}" />
        <meta property="og:image:height" content="{{ idea.picture_social.height }}" />
    {% endif %}
    <meta property="og:description" content="{{ idea.tranlated_content }}" />
    <meta property="og:site_name" content="Crudl" />
    <meta property="og:locale" content="{{ LANGUAGE_CODE }}" />
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@DjangoTricks">
    <meta name="twitter:creator" content="@TripleeO">
    <meta name="twitter:url" content="{{ WEBSITE_URL }} {{ request.path }}">
    <meta name="twitter:title" content="{{ idea.translated_title }}">
    <meta name="twitter:description" content="{{ idea.translated_content }}">
    {% if idea.picture_social %}
        <meta name="twitter:image" content="{{ idea.picture_social.url }}">
    {% endif %}
    {% render_json_ld idea.structured_data %}
{% endblock meta_tags %}
{% block content %}
<div class="ideas">
    <div class="idea-detail">
        {% if request.user.is_authenticated and request.user == idea.author %}
        <a href="{% url 'ideas:change_idea' pk=idea.pk %}" class="btn btn-primary">{% trans "Change this idea" %}</a>
        <a href="{% url 'ideas:delete_idea' pk=idea.pk %}" class="btn btn-danger">{% trans "Delete this idea" %}</a>
        {% endif %}
        <div class="image">
            <img src="{{ idea.watermarked_picture_large.url }}" alt="{{ idea.title }}" />
        </div>
        <h1 class="title">
            {% blocktrans trimmed with title=idea.translated_title %} 
                {{ idea.title }}
            {% endblocktrans %}
        </h1>
        <p>
            {% for category in idea.categories.all %}
                <span class="badge badge-pill badge-info">
                    {{ category.translated_title }}
                </span>
            {% endfor %}
        </p>
        <div class="content">{{ idea.content }}</div>
        <span class="rating">{{ idea.rating }}</span>
        <div class="author">{{ idea.author.username }}</div>
        <a href="{% url 'ideas:download_idea_picture' pk=idea.pk %}" class="btn btn-primary">{% trans "Download picture" %}</a>
    </div>
</div>
{% endblock content %}

src/crudl/crudl/templates/ideas/idea_form.html
{% extends "crudl/base.html" %}
{% load i18n crispy_forms_tags static %}
{% block content %}
    <a href="{% url 'ideas:idea_list' %}">{% trans "List of ideas" %}</a>
    <h1>
        {% if idea %}
            {% blocktrans trimmed with title=idea.translated_title %}
                Change Idea "{{ title }}"
            {% endblocktrans %}
        {% else %}
            {% trans "Add Idea" %}
        {% endif %}
    </h1>
    {% crispy form %}
{% endblock content %}
{% block js %}
    <script src="{% static 'site/js/inlines.js' %}"></script>
    <script src="{% static 'site/js/main.js' %}"></script>
{% endblock js %}

src/crudl/crudl/templates/ideas/idea_handout_pdf.html
{% extends "base_pdf.html" %}
{% load i18n qr_code %}
{% block content %}
    <h1 class="h3">{% trans "Handout" %}</h1>
    <h2 class="h1">{{ idea.translated_title }}</h2>
    <img src="{{ idea.picture_large.url }}" alt="{{ idea.translated_title }}" class="img-responsive w-100" />
    <div class="my-3">{{ idea.translated_content | linebreaks|urlize }}</div>
    <p>
        {% for category in idea.categories.all %}
            <span class="badge badge-pill badge-info">
                {{ category.translated_title }}
            </span>
        {% endfor %}
    </p>
    <h4>{% trans "See more information online:" %}</h4>
    {% qr_from_text idea.get_url size=20 border=0 as svg_code %}
    <img alt="" src="data:image/svg+xml, {{ svg_code|urlencode }}" />
    <p class="mt-3 text-break">{{ idea.get_url }}</p>
{% endblock content %}

src/crudl/crudl/templates/ideas/idea_list.html
{% extends "crudl/base.html" %}
{% load i18n utility_tags crispy_forms_tags %}
{% block sidebar%}
    {% include "ideas/includes/filters.html" %}
    {% crispy form %}
{% endblock sidebar%}
{% block main %}
<h1>{% trans "Ideas" %}</h1>
{% if object_list %}
    {% for idea in object_list %}
        <div class="card">
            <div class="card-detail">
                <div class="card-image">
                    <img src="{{ idea.picture_thumbnail.url }}" alt="{{ idea.title }}">
                </div>
                <h1><a class="d-block my-3" href="{{ idea.get_url_path }}">{{ idea.title }}</a></h1>
                <div class="card-body">
                    <p class="card-text">{{ idea.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include "misc/includes/pagination.html" %}
{% else %}
    <p>{% trans "There are no ideas yet." %}</p>
{% endif %}
{% endblock main %}

src/crudl/crudl/templates/ideas/idea_search.html
{% extends "crudl/base.html" %}
{% load i18n crispy_forms_tags %}
{% block sidebar %}
    {% crispy form %}
{% endblock sidebar%}
{% block content %}
    <h1>{% trans "Search Results" %}</h1>
    {% if object_list %}
        {% for idea in object_list %}
            <a href="{{ idea.get_url_path }}" class="d-block my-3">
                <div class="card">
                    <img src="{{ idea.picture_thumbnail_url }}" alt="{{ idea.translated_title }}" />
                    <div class="card-body">
                        <p class="card-text">
                            {{ idea.translated_title }}
                        </p>
                    </div>
                </div>
            </a>
        {% endfor %}
        {% include "misc/includes/pagination.html" %}
    {% else %}
        <p>{% trans "No ideas found." %}</p>
    {% endif %}
{% endblock content %}